import type { Lang } from "@/lib/i18n";

const en = {
  skip: "Skip to content",
  topStrip: "Official profile · Jhandi Raj, District Kheri",
  menu: "Menu",
  closeMenu: "Close menu",
  language: "Language",
  switchTo: "Switch language",
  breadcrumbs: "Breadcrumb",
  home: "Home",

  nav: {
    home: "Home",
    about: "About & Journey",
    biography: "Biography",
    education: "Education & Work",
    heritage: "Family & Heritage",
    journey: "Journey",
    politicalJourney: "Political Journey",
    milestones: "Milestones",
    publicLife: "Public Life",
    publicWork: "Public Work",
    publicConnect: "Public Connect",
    regionalIssues: "Regional Issues",
    communityFaith: "Community & Faith",
    media: "Media",
    photos: "Photos",
    videos: "Videos",
    updates: "Updates",
    contact: "Contact",
  },

  hero: {
    eyebrow: "Official profile",
    lead: "Of the Jhandi Raj family of Kheri district. A mechanical engineer by training, a farmer by occupation, and active in the Bharatiya Janata Party.",
    cta: "Explore profile",
    ctaSecondary: "Contact",
    portraitAlt: "Raja Raj Rajeshwar Singh walking, in a red waistcoat and white kurta pyjama",
  },

  sections: {
    introduction: "Introduction",
    about: "About",
    aboutLead: "An engineer by training, a farmer by occupation, and a public worker in his home region.",
    readBiography: "Read the full biography",
    heritage: "Family & Heritage",
    heritageTitle: "A house known for its gifts of land",
    heritageLead:
      "The Jhandi Raj family gave land to temples, to the city of Lucknow, and to a mosque, a Karbala and a gurudwara.",
    readHeritage: "Read the family history",
    journey: "Political journey",
    journeyLead: "His own path in the Bharatiya Janata Party, and the political record of his father.",
    readJourney: "See the full journey",
    publicLife: "Public life",
    publicLifeLead: "What has been documented of his work, and of the family's public record.",
    explore: "Read more",
    recentTitle: "Featured video",
    viewMedia: "All media",
    meetings: "Meetings & Interactions",
    meetingsLead: "Selected meetings and interactions from public life.",
    updates: "Latest updates",
    viewUpdates: "All updates",
    socialTitle: "Follow on social media",
    socialLead: "The official pages of Raja Raj Rajeshwar Singh.",
    contactTitle: "Get in touch",
    contactLead:
      "For general enquiries, media requests, public programmes or to request a meeting, please use the form below.",
  },

  biography: {
    title: "Biography",
    lead: "Raja Raj Rajeshwar Singh, known as Jhandi-Raj, is from Jhandi Raj in Kheri district.",
    description:
      "Biography of Raja Raj Rajeshwar Singh (Jhandi-Raj): education, occupation, public engagement and his association with the Bharatiya Janata Party.",
    alsoSee: "Also see",
  },
  heritage: {
    title: "Family & Heritage",
    description:
      "The history of the Jhandi Raj family of Kheri, Awadh: its Chauhan origins, Raja Raghubar Singh, and the land given to temples, Jhandi Park in Lucknow and other communities.",
    origins: "Origins",
    raghubar: "Raja Raghubar Singh",
    gifts: "Gifts of land",
    gifts_lead: "The family's record of donations, as set out in its own history.",
    fort: "The fort today",
    after: "After Raja Raghubar Singh",
    sourcesLabel: "Sources",
  },
  journey: {
    title: "Political Journey",
    description:
      "The political and public journey of Raja Raj Rajeshwar Singh, and the earlier political record of his father, Raja Brajraj Singh.",
    own: "Raja Raj Rajeshwar Singh",
    ownLead: "In public life and the Bharatiya Janata Party",
    fatherLabel: "His father",
    fatherNote: "The record below is his father's, not his own.",
  },
  milestones: {
    title: "Milestones",
    description:
      "A dated timeline of the Jhandi Raj family and of Raja Brajraj Singh's public life, drawn from documented sources.",
    lead: "Dates are given only where the source material records them.",
    all: "All",
    family: "Family history",
    father: "Raja Brajraj Singh",
    filter: "Filter timeline",
  },
  publicLife: {
    title: "Public Life",
    description:
      "Public work, regional issues and community contributions associated with Raja Raj Rajeshwar Singh and the Jhandi Raj family.",
    lead: "Public work, regional issues, community contributions and recorded public interactions.",
    onIndex: "On this page",
  },
  media: {
    title: "Media",
    description:
      "Official photographs and videos of Raja Raj Rajeshwar Singh, including a visit to flood-affected areas with relief kit distribution. Speeches and press coverage will be added as they are published.",
    lead: "Official videos, photographs and moments from public life.",
    body: "Meetings, field visits, community interactions and other public engagements, recorded in photographs and video.",
    heroLinks: { photos: "Photographs", videos: "Videos", updates: "Updates" },
    videos: "Videos",
    photos: "Photographs",
    play: "Play video",
    all: "All",
    open: "Open image",
    close: "Close",
    previous: "Previous image",
    next: "Next image",
    counter: "of",
    filter: "Filter media",
  },
  updates: {
    title: "Updates",
    description: "Latest updates on the public activity of Raja Raj Rajeshwar Singh.",
    eyebrow: "Latest activities",
    lead: "Latest activities, field visits and public engagements from Jhandi-Raj.",
    body: "Follow recent visits, community interactions, public-service activities, local issues and important developments from the field.",
    points: ["Latest activities", "Field visits", "Public service"],
    readMore: "Read more",
    morePhotos: "More photographs",
    featured: "Featured",
  },
  contact: {
    title: "Contact",
    description:
      "Send an enquiry to Raja Raj Rajeshwar Singh: general enquiries, media, public programmes and meeting requests.",
    social: "Social media",
    region: "Region",
    heroTitle: "Get in touch",
    lead: "Connect regarding public matters, community concerns and enquiries.",
    note: "Enquiries are sent by email.",
    form: {
      name: "Full name",
      mobile: "Mobile number",
      email: "Email (optional)",
      subject: "Subject",
      type: "Enquiry type",
      message: "Message",
      submit: "Send enquiry",
      sending: "Sending…",
      types: {
        general: "General enquiry",
        media: "Media",
        programme: "Public programme",
        meeting: "Meeting request",
        other: "Other",
      },
      errors: {
        name: "Please enter your full name.",
        mobile: "Enter a valid 10-digit mobile number.",
        email: "Enter a valid email address.",
        subject: "Please add a subject.",
        message: "Please write a message of at least 10 characters.",
      },
      success: "Thank you. Your enquiry has been sent.",
      failure: "Your enquiry could not be sent. Please try again in a little while.",
      required: "Required",
    },
  },
  legal: {
    privacy: "Privacy Policy",
    terms: "Terms",
    updated: "Last updated",
  },
  feed: {
    title: "Latest from social media",
    lead: "Recent posts and videos from the official Facebook page and YouTube channel.",
    facebook: "Facebook",
    facebookOpen: "Open the Facebook page",
    facebookLoading: "Loading the latest posts…",
    facebookNote: "This panel is provided by Facebook and may set Facebook cookies.",
    youtube: "Latest videos",
    youtubeOpen: "Open the YouTube channel",
    watch: "Watch on YouTube",
    empty: "The latest videos could not be loaded right now. Please visit the channel directly.",
  },
  footer: {
    tagline: "Official profile of Raja Raj Rajeshwar Singh (Jhandi-Raj).",
    explore: "Explore",
    connect: "Connect",
    rights: "All rights reserved.",
    creditLabel: "Digital experience partner",
  },
  assistant: {
    button: "Ask assistant",
    title: "Profile assistant",
    hello: "How can I help you?",
    note: "Answers come only from the official profile on this website.",
    placeholder: "Type your question",
    send: "Send",
    close: "Close assistant",
    open: "Open assistant",
    suggested: "Suggested questions",
    unavailable: "This information is not available in the official profile.",
    questions: [
      "Who is Raja Rajeshwar Singh?",
      "Tell me about his background.",
      "What is his political journey?",
      "What public work is documented?",
      "Show latest updates.",
      "Show photos.",
      "How can I contact him?",
    ],
  },
};

export type Dict = typeof en;

const hi: Dict = {
  skip: "मुख्य सामग्री पर जाएँ",
  topStrip: "आधिकारिक प्रोफ़ाइल · झंडी राज, जनपद खीरी",
  menu: "मेनू",
  closeMenu: "मेनू बंद करें",
  language: "भाषा",
  switchTo: "भाषा बदलें",
  breadcrumbs: "ब्रेडक्रम्ब",
  home: "मुख्य पृष्ठ",

  nav: {
    home: "मुख्य पृष्ठ",
    about: "परिचय एवं यात्रा",
    biography: "जीवन परिचय",
    education: "शिक्षा और कार्य",
    heritage: "परिवार एवं विरासत",
    journey: "यात्रा",
    politicalJourney: "राजनीतिक यात्रा",
    milestones: "प्रमुख पड़ाव",
    publicLife: "सार्वजनिक जीवन",
    publicWork: "जनसेवा",
    publicConnect: "जनसंपर्क",
    regionalIssues: "क्षेत्रीय मुद्दे",
    communityFaith: "समाज और आस्था",
    media: "मीडिया",
    photos: "चित्र",
    videos: "वीडियो",
    updates: "समाचार",
    contact: "संपर्क",
  },

  hero: {
    eyebrow: "आधिकारिक प्रोफ़ाइल",
    lead: "खीरी जनपद के झंडी राज परिवार से। शिक्षा से मैकेनिकल इंजीनियर, व्यवसाय से किसान, और भारतीय जनता पार्टी में सक्रिय।",
    cta: "प्रोफ़ाइल देखें",
    ctaSecondary: "संपर्क करें",
    portraitAlt: "लाल जैकेट और सफ़ेद कुर्ता-पायजामा में चलते हुए राजा राज राजेश्वर सिंह",
  },

  sections: {
    introduction: "परिचय",
    about: "जीवन परिचय",
    aboutLead: "शिक्षा से इंजीनियर, व्यवसाय से किसान, और अपने क्षेत्र में जनसेवा से जुड़े हुए।",
    readBiography: "पूरा जीवन परिचय पढ़ें",
    heritage: "परिवार एवं विरासत",
    heritageTitle: "भूमि-दान के लिए जाना जाने वाला घराना",
    heritageLead:
      "झंडी राज परिवार ने मंदिरों, लखनऊ नगर, तथा मस्जिद, करबला और गुरुद्वारे के लिए भूमि दान की।",
    readHeritage: "पारिवारिक इतिहास पढ़ें",
    journey: "राजनीतिक यात्रा",
    journeyLead: "भारतीय जनता पार्टी में उनका अपना सफ़र, और उनके पिता का राजनीतिक अभिलेख।",
    readJourney: "पूरी यात्रा देखें",
    publicLife: "सार्वजनिक जीवन",
    publicLifeLead: "उनके कार्यों और परिवार की सार्वजनिक भूमिका का अब तक दर्ज विवरण।",
    explore: "आगे पढ़ें",
    recentTitle: "विशेष वीडियो",
    viewMedia: "सारा मीडिया",
    meetings: "भेंट एवं संवाद",
    meetingsLead: "सार्वजनिक जीवन से जुड़ी प्रमुख भेंट एवं संवाद।",
    updates: "ताज़ा समाचार",
    viewUpdates: "सभी समाचार",
    socialTitle: "सोशल मीडिया पर जुड़ें",
    socialLead: "राजा राज राजेश्वर सिंह के आधिकारिक पेज।",
    contactTitle: "संपर्क करें",
    contactLead:
      "सामान्य पूछताछ, मीडिया अनुरोध, सार्वजनिक कार्यक्रम या भेंट के अनुरोध के लिए कृपया नीचे दिया फ़ॉर्म भरें।",
  },

  biography: {
    title: "जीवन परिचय",
    lead: "राजा राज राजेश्वर सिंह, जो झंडी-राज के नाम से जाने जाते हैं, खीरी जनपद के झंडी राज से हैं।",
    description:
      "राजा राज राजेश्वर सिंह (झंडी-राज) का जीवन परिचय: शिक्षा, व्यवसाय, जनसंपर्क और भारतीय जनता पार्टी से उनका जुड़ाव।",
    alsoSee: "यह भी देखें",
  },
  heritage: {
    title: "परिवार एवं विरासत",
    description:
      "अवध के खीरी जनपद के झंडी राज परिवार का इतिहास: चौहान मूल, राजा रघुबर सिंह, तथा मंदिरों, लखनऊ के झंडी पार्क और अन्य समुदायों के लिए दी गई भूमि।",
    origins: "मूल",
    raghubar: "राजा रघुबर सिंह",
    gifts: "भूमि-दान",
    gifts_lead: "परिवार के अपने इतिहास में दर्ज दान का विवरण।",
    fort: "किला आज",
    after: "राजा रघुबर सिंह के बाद",
    sourcesLabel: "स्रोत",
  },
  journey: {
    title: "राजनीतिक यात्रा",
    description:
      "राजा राज राजेश्वर सिंह की राजनीतिक और सार्वजनिक यात्रा, तथा उनके पिता राजा ब्रजराज सिंह का पूर्व राजनीतिक अभिलेख।",
    own: "राजा राज राजेश्वर सिंह",
    ownLead: "सार्वजनिक जीवन और भारतीय जनता पार्टी में",
    fatherLabel: "उनके पिता",
    fatherNote: "नीचे का विवरण उनके पिता का है, उनका अपना नहीं।",
  },
  milestones: {
    title: "प्रमुख पड़ाव",
    description:
      "झंडी राज परिवार और राजा ब्रजराज सिंह के सार्वजनिक जीवन की, प्रलेखित स्रोतों पर आधारित तिथिवार समय-रेखा।",
    lead: "तिथियाँ केवल वहीं दी गई हैं जहाँ स्रोत सामग्री में दर्ज हैं।",
    all: "सभी",
    family: "पारिवारिक इतिहास",
    father: "राजा ब्रजराज सिंह",
    filter: "समय-रेखा छानें",
  },
  publicLife: {
    title: "सार्वजनिक जीवन",
    description:
      "राजा राज राजेश्वर सिंह और झंडी राज परिवार से जुड़ी जनसेवा, क्षेत्रीय मुद्दे और सामुदायिक योगदान।",
    lead: "जनसेवा, क्षेत्रीय मुद्दे, सामुदायिक योगदान और दर्ज जनसंपर्क।",
    onIndex: "इस पृष्ठ पर",
  },
  media: {
    title: "मीडिया",
    description:
      "राजा राज राजेश्वर सिंह के आधिकारिक वीडियो और छायाचित्र, जिनमें बाढ़ प्रभावित क्षेत्रों के भ्रमण और राहत किट वितरण का वीडियो भी शामिल है। भाषण और प्रेस कवरेज प्रकाशित होने पर जोड़े जाएँगे।",
    lead: "आधिकारिक वीडियो, छायाचित्र और सार्वजनिक जीवन के क्षण।",
    body: "बैठकें, क्षेत्र के भ्रमण, जनसंवाद और अन्य सार्वजनिक कार्यक्रम, छायाचित्रों और वीडियो के रूप में।",
    heroLinks: { photos: "छायाचित्र", videos: "वीडियो", updates: "समाचार" },
    videos: "वीडियो",
    photos: "छायाचित्र",
    play: "वीडियो चलाएँ",
    all: "सभी",
    open: "चित्र खोलें",
    close: "बंद करें",
    previous: "पिछला चित्र",
    next: "अगला चित्र",
    counter: "/",
    filter: "मीडिया छानें",
  },
  updates: {
    title: "समाचार",
    description: "राजा राज राजेश्वर सिंह की सार्वजनिक गतिविधियों के ताज़ा समाचार।",
    eyebrow: "हाल की गतिविधियाँ",
    lead: "हाल की गतिविधियों, क्षेत्रीय दौरों और जनसंपर्क से जुड़ी प्रमुख जानकारियाँ।",
    body: "क्षेत्र में किए जा रहे दौरों, जनसंपर्क, जनसेवा के कार्यों, स्थानीय मुद्दों और महत्वपूर्ण गतिविधियों की ताज़ा जानकारी यहाँ देखें।",
    points: ["हाल की गतिविधियाँ", "क्षेत्रीय दौरे", "जनसेवा"],
    readMore: "आगे पढ़ें",
    morePhotos: "और छायाचित्र",
    featured: "विशेष",
  },
  contact: {
    title: "संपर्क",
    description:
      "राजा राज राजेश्वर सिंह को पूछताछ भेजें: सामान्य पूछताछ, मीडिया, सार्वजनिक कार्यक्रम और भेंट का अनुरोध।",
    social: "सोशल मीडिया",
    region: "क्षेत्र",
    heroTitle: "संपर्क करें",
    lead: "सार्वजनिक विषयों, स्थानीय चिंताओं और पूछताछ के लिए संपर्क करें।",
    note: "पूछताछ ईमेल द्वारा भेजी जाती है।",
    form: {
      name: "पूरा नाम",
      mobile: "मोबाइल नंबर",
      email: "ईमेल (वैकल्पिक)",
      subject: "विषय",
      type: "पूछताछ का प्रकार",
      message: "संदेश",
      submit: "पूछताछ भेजें",
      sending: "भेजा जा रहा है…",
      types: {
        general: "सामान्य पूछताछ",
        media: "मीडिया",
        programme: "सार्वजनिक कार्यक्रम",
        meeting: "भेंट का अनुरोध",
        other: "अन्य",
      },
      errors: {
        name: "कृपया अपना पूरा नाम लिखें।",
        mobile: "10 अंकों का सही मोबाइल नंबर लिखें।",
        email: "सही ईमेल पता लिखें।",
        subject: "कृपया विषय लिखें।",
        message: "कृपया कम से कम 10 अक्षरों का संदेश लिखें।",
      },
      success: "धन्यवाद। आपकी पूछताछ भेज दी गई है।",
      failure: "आपकी पूछताछ भेजी नहीं जा सकी। कृपया थोड़ी देर बाद पुनः प्रयास करें।",
      required: "आवश्यक",
    },
  },
  legal: {
    privacy: "गोपनीयता नीति",
    terms: "उपयोग की शर्तें",
    updated: "अंतिम अद्यतन",
  },
  feed: {
    title: "सोशल मीडिया पर ताज़ा",
    lead: "आधिकारिक फ़ेसबुक पेज और यूट्यूब चैनल की हाल की पोस्ट और वीडियो।",
    facebook: "फ़ेसबुक",
    facebookOpen: "फ़ेसबुक पेज खोलें",
    facebookLoading: "ताज़ा पोस्ट लोड हो रही हैं…",
    facebookNote: "यह पैनल फ़ेसबुक द्वारा दिया जाता है और फ़ेसबुक कुकीज़ लगा सकता है।",
    youtube: "नवीनतम वीडियो",
    youtubeOpen: "यूट्यूब चैनल खोलें",
    watch: "यूट्यूब पर देखें",
    empty: "नवीनतम वीडियो अभी लोड नहीं हो सके। कृपया चैनल पर सीधे जाएँ।",
  },
  footer: {
    tagline: "राजा राज राजेश्वर सिंह (झंडी-राज) की आधिकारिक प्रोफ़ाइल।",
    explore: "देखें",
    connect: "जुड़ें",
    rights: "सर्वाधिकार सुरक्षित।",
    creditLabel: "डिजिटल एक्सपीरियंस पार्टनर",
  },
  assistant: {
    button: "सहायक से पूछें",
    title: "प्रोफ़ाइल सहायक",
    hello: "मैं आपकी क्या सहायता कर सकता हूँ?",
    note: "उत्तर केवल इस वेबसाइट की आधिकारिक प्रोफ़ाइल से दिए जाते हैं।",
    placeholder: "अपना प्रश्न लिखें",
    send: "भेजें",
    close: "सहायक बंद करें",
    open: "सहायक खोलें",
    suggested: "सुझाए गए प्रश्न",
    unavailable: "यह जानकारी आधिकारिक प्रोफ़ाइल में उपलब्ध नहीं है।",
    questions: [
      "राज राजेश्वर सिंह कौन हैं?",
      "उनकी पृष्ठभूमि के बारे में बताइए।",
      "उनकी राजनीतिक यात्रा क्या है?",
      "कौन-सा सार्वजनिक कार्य दर्ज है?",
      "ताज़ा समाचार दिखाइए।",
      "चित्र दिखाइए।",
      "उनसे संपर्क कैसे करें?",
    ],
  },
};

export const dictionaries: Record<Lang, Dict> = { en, hi };
export const getDict = (lang: Lang) => dictionaries[lang];
