/** Generated by scripts/update-youtube-snapshot.mjs. Used only when YouTube cannot be read live. */
export const youtubeSnapshot: { id: string; title: string; published: string }[] = [
  { id: "Tt8xe6cLrBA", title: "निघासन की बाढ़ की समस्या से निजात दिलाने हेतु संघर्ष जारी रहेगा।", published: "2026-09-07T12:05:22+00:00" },
  { id: "zg7T19UAaUo", title: "निघासन तमोलिनपुरवा में बंधा काटा जाना अत्यंत दुर्भाग्यपूर्ण।", published: "2026-08-25T07:04:38+00:00" },
  { id: "bqdit5Bk1d4", title: "निघासन तमोलिनपुरवा में बंधा काटा जाना अत्यंत दुर्भाग्यपूर्ण।", published: "2026-08-25T07:00:12+00:00" },
  { id: "SsED_qIGWUo", title: "निघासन में शारदा नदी से आने वाली बाढ़ की समस्याओं हेतु प्रयासरत।", published: "2026-08-24T05:51:05+00:00" },
  { id: "_DPSfOE9VMg", title: "निघासन बाढ़ समस्याओं के समाधान हेतु निरंतर संघर्ष व प्रयास जारी रहेगा ।", published: "2026-08-24T05:44:11+00:00" },
  { id: "WUlHBQav0OY", title: "निघासन में बाढ़-जलभराव से राहत हेतु ठाकुर पुरवा में ऊंचे पुल की मांग की।", published: "2026-08-22T05:51:42+00:00" },
];
